### ISSUE TITLE
SyntaxError: invalid syntax while running

### ISSUE THREAD

**Issue by Ferynix** [Malar10/td-xml-helper#1]
![image](https://github.com/Malar10/td-xml-helper/assets/44554976/52fcc85a-a1f1-4de4-b8b3-fbec1e5ccd3b)

Seems to be broken on my end, I have python 3.11.7 installed, so I dont know if thats part of it

**Comment by Malar10** [comment]
Hi the proper usage is to prefix the commands with "py" or "python" to make python run the file like so `py xmlhelper.py -h`
on my machine, simply writing `xmlhelper.py -h` will make vs code open the file but not run it
I'll update the readme to make that more clear

also I tried changing my python version to 3.11.7 but couldn't replicate that error

**Comment by Ferynix** [comment]
Closed since we solved this outside of github
